---
efiBootLoader: "grub"
kernel: "/boot/vmlinuz-linux-zen"
img: "/boot/initramfs-linux-zen.img"
fallback: "/boot/initramfs-linux-zen-fallback.img"
timeout: 3
grubInstall: "grub-install"
grubMkconfig: "grub-mkconfig"
grubCfg: "/boot/grub/grub.cfg"
