---
dontChroot: false
timeout: 600
packagechooser_bytefall:
  bytefall-profile-default:
    - "-pacman -Rns --noconfirm git gcc clang make cmake ninja pkgconf gdb strace lldb python python-pip nodejs npm rustup go docker docker-compose podman qemu-desktop virt-manager linux-zen-headers base-devel jdk-openjdk qtcreator code neovim tmux wireshark-qt yq htop"
  bytefall-profile-dev:
    - "/usr/bin/true"
  bytefall-profile-server:
    - "-pacman -Rns --noconfirm plasma-meta kde-system-meta sddm konsole dolphin ark spectacle kate kcalc kvantum kvantum-qt5 breeze-gtk materia-gtk-theme papirus-icon-theme qt6-base qt6-declarative kirigami qqc2-desktop-style xdg-desktop-portal-kde powerdevil plasma-nm bluedevil fastfetch starship git gcc clang make cmake ninja pkgconf gdb strace lldb python python-pip nodejs npm rustup go docker docker-compose podman qemu-desktop virt-manager linux-zen-headers base-devel jdk-openjdk qtcreator code neovim tmux wireshark-qt firefox yq htop"
    - "-rm -f /etc/xdg/autostart/bytefall-welcome.desktop /etc/xdg/autostart/bytefall-plasma-setup.desktop"
    - "-rm -f /home/@@USER@@/.config/autostart/bytefall-plasma-setup.desktop"
    - "-rm -f /home/@@USER@@/.config/ksplashrc"
    - "-rm -rf /usr/share/wallpapers/BytefallAurora /usr/share/wallpapers/BytefallClassic /usr/share/plasma/look-and-feel/org.bytefall.desktop"
    - "-systemctl disable sddm.service"
    - "-rm -f /etc/systemd/system/display-manager.service /etc/systemd/system/graphical.target.wants/sddm.service"
    - "systemctl set-default multi-user.target"
