---
efiSystemPartition: "/boot/efi"
userSwapChoices:
  - none
  - small
  - suspend
drawNestedPartitions: true
defaultFileSystemType: "ext4"
availableFileSystemTypes:
  - "ext4"
  - "btrfs"
  - "xfs"
allowManualPartitioning: true
allowReformatting: true
initialPartitioningChoice: "erase"
enableLuksAutomatedPartitioning: true

