---
dontChroot: true
script:
  - command: "mkdir -p \"${ROOT}/boot\""
    timeout: 10
  - command: "install -Dm644 /run/archiso/bootmnt/bytefall/boot/x86_64/vmlinuz-linux-zen \"${ROOT}/boot/vmlinuz-linux-zen\""
    timeout: 30
