---
defaultGroups:
  - wheel
  - users
  - audio
  - video
  - storage
  - network
  - docker
autologinGroup: autologin
sudoersGroup: wheel
userShell: /usr/bin/fish
setRootPassword: false
doAutologin: false
allowWeakPasswords: false
