---
showSupportUrl: false
showKnownIssuesUrl: false
showReleaseNotesUrl: false
requirements:
  requiredStorage: 16
  requiredRam: 2.0
  internetCheckUrl: https://archlinux.org
  check:
    - storage
    - ram
  required:
    - storage
    - ram
